#!/usr/bin/env python3
"""
Layer 2: Plane.so Database Override Script
==========================================
Reads migration_mapping.json and directly updates Plane's PostgreSQL
database to restore original timestamps and authorship from Taiga.

Usage:
    python update_plane_db.py [migration_mapping.json]
"""

import json
import os
import sys
import html
import re
from uuid import uuid4
from datetime import datetime, timezone

try:
    import psycopg  # psycopg (v3)

    DB_DRIVER = "psycopg"
    DBError = psycopg.Error

    def db_connect(dsn):
        return psycopg.connect(dsn)

except ImportError:  # pragma: no cover
    import psycopg2  # type: ignore

    DB_DRIVER = "psycopg2"
    DBError = psycopg2.Error

    def db_connect(dsn):
        return psycopg2.connect(dsn)

# ==========================================
# CONFIGURATION
# ==========================================

# Plane.so PostgreSQL Database Connection
DB_HOST = os.environ.get("PLANE_DB_HOST", "plane-db")
DB_PORT = os.environ.get("PLANE_DB_PORT", "5432")
DB_NAME = os.environ.get("PLANE_DB_NAME", "plane")
DB_USER = os.environ.get("PLANE_DB_USER", "plane")
DB_PASSWORD = os.environ.get("PLANE_DB_PASSWORD", os.environ.get("POSTGRES_PASSWORD", "plane"))
MIGRATE_WIKI_PAGES_VIA_DB = os.environ.get("MIGRATE_WIKI_PAGES_VIA_DB", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}
PLANE_ROLE_ADMIN = int(os.environ.get("PLANE_ROLE_ADMIN", "20"))
PLANE_ROLE_MEMBER = int(os.environ.get("PLANE_ROLE_MEMBER", "15"))
PLANE_ROLE_GUEST = int(os.environ.get("PLANE_ROLE_GUEST", "5"))

# Mapping file path (generated by Layer 1)
MAPPING_FILE = "migration_mapping.json"

# ==========================================
# DATABASE FUNCTIONS
# ==========================================

USER_ID_CACHE = {}
PROJECT_WORKSPACE_CACHE = {}


def get_db_connection():
    """Connect to Plane's PostgreSQL database."""
    try:
        dsn = f"host={DB_HOST} port={DB_PORT} dbname={DB_NAME} user={DB_USER} password={DB_PASSWORD}"
        conn = db_connect(dsn)
        print(f"✅ Connected to PostgreSQL ({DB_DRIVER}): {DB_HOST}:{DB_PORT}/{DB_NAME}")
        return conn
    except DBError as e:
        print(f"❌ Database connection failed: {e}")
        sys.exit(1)


def load_mapping(filepath):
    """Load migration_mapping.json."""
    try:
        with open(filepath, "r") as f:
            data = json.load(f)
        print(f"✅ Loaded mapping from {filepath}")
        return data
    except FileNotFoundError:
        print(f"❌ {filepath} not found. Run Layer 1 first.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Invalid JSON in {filepath}: {e}")
        sys.exit(1)


def reset_runtime_caches():
    """Clear per-run caches."""
    USER_ID_CACHE.clear()
    PROJECT_WORKSPACE_CACHE.clear()


def normalize_email(value):
    if not isinstance(value, str):
        return ""
    email = value.strip().lower()
    return email if "@" in email else ""


def lookup_user_id(cursor, email):
    """Look up a Plane user ID by email address."""
    if not email:
        return None
    cache_key = normalize_email(email)
    if cache_key and cache_key in USER_ID_CACHE:
        return USER_ID_CACHE[cache_key]
    try:
        cursor.execute("SELECT id FROM users WHERE email = %s", (email,))
        row = cursor.fetchone()
        user_id = row[0] if row else None
        if cache_key:
            USER_ID_CACHE[cache_key] = user_id
        return user_id
    except DBError:
        if cache_key:
            USER_ID_CACHE[cache_key] = None
        return None


def get_project_workspace_id(cursor, project_id, cache=None):
    """Get workspace id for a project with simple cache."""
    if not project_id:
        return None
    cache = cache if cache is not None else PROJECT_WORKSPACE_CACHE
    if project_id in cache:
        return cache[project_id]
    cursor.execute("SELECT workspace_id FROM projects WHERE id = %s", (project_id,))
    row = cursor.fetchone()
    workspace_id = row[0] if row else None
    cache[project_id] = workspace_id
    return workspace_id


def get_template_user(cursor):
    cursor.execute(
        """
        SELECT password, avatar, last_location, created_location, user_timezone,
               last_login_ip, last_logout_ip, last_login_medium, last_login_uagent,
               is_email_valid
        FROM users
        ORDER BY created_at ASC
        LIMIT 1
        """
    )
    row = cursor.fetchone()
    if not row:
        raise RuntimeError("No template user found in Plane DB; cannot auto-create users.")
    return {
        "password": row[0],
        "avatar": row[1] or "",
        "last_location": row[2] or "",
        "created_location": row[3] or "",
        "user_timezone": row[4] or "UTC",
        "last_login_ip": row[5] or "",
        "last_logout_ip": row[6] or "",
        "last_login_medium": row[7] or "email",
        "last_login_uagent": row[8] or "",
        "is_email_valid": True if row[9] is None else bool(row[9]),
    }


def get_template_workspace_member(cursor):
    cursor.execute(
        """
        SELECT role, view_props, default_props, issue_props
        FROM workspace_members
        ORDER BY created_at ASC
        LIMIT 1
        """
    )
    row = cursor.fetchone()
    if not row:
        return {"role": 20, "view_props": {}, "default_props": {}, "issue_props": {}}
    return {"role": row[0], "view_props": row[1], "default_props": row[2], "issue_props": row[3]}


def get_template_project_member(cursor):
    cursor.execute(
        """
        SELECT role, view_props, default_props, preferences, sort_order
        FROM project_members
        ORDER BY created_at ASC
        LIMIT 1
        """
    )
    row = cursor.fetchone()
    if not row:
        return {
            "role": 20,
            "view_props": {},
            "default_props": {},
            "preferences": {},
            "sort_order": 65535,
        }
    return {
        "role": row[0],
        "view_props": row[1],
        "default_props": row[2],
        "preferences": row[3],
        "sort_order": row[4],
    }


def to_json(val):
    if isinstance(val, str):
        return val
    return json.dumps(val or {})


def role_info_lookup(role_map, role_name):
    if not isinstance(role_map, dict):
        return None
    if not role_name:
        return None
    info = role_map.get(role_name)
    if isinstance(info, dict):
        return info
    key_lower = role_name.strip().lower()
    for key, val in role_map.items():
        if isinstance(key, str) and key.strip().lower() == key_lower and isinstance(val, dict):
            return val
    return None


def map_taiga_membership_role(role_name, is_admin, role_permissions):
    """Map Taiga membership role semantics to Plane role values."""
    if is_admin:
        return PLANE_ROLE_ADMIN

    normalized = (role_name or "").strip().lower()
    if normalized:
        if any(k in normalized for k in ("stakeholder", "guest", "viewer", "read only", "read-only")):
            return PLANE_ROLE_GUEST
        if any(k in normalized for k in ("owner", "admin", "manager", "lead", "product owner", "product-owner")):
            return PLANE_ROLE_MEMBER

    perms = set(role_permissions or [])
    if not perms:
        return PLANE_ROLE_MEMBER

    if any(p.startswith(("add_", "modify_", "delete_")) for p in perms):
        return PLANE_ROLE_MEMBER
    return PLANE_ROLE_GUEST


def build_taiga_membership_role_targets(mapping):
    """
    Build role targets from Taiga memberships.
    Returns dict: (email, project_id) -> {"role": int, "created_at": str|None}
    """
    targets = {}
    roles_by_project = mapping.get("taiga_roles") or {}

    for entry in mapping.get("taiga_memberships", []) or []:
        if not isinstance(entry, dict):
            continue
        email = normalize_email(entry.get("email") or entry.get("user"))
        project_id = entry.get("plane_project_id")
        if not email or not project_id:
            continue

        role_name = entry.get("role")
        role_info = role_info_lookup(roles_by_project.get(project_id), role_name)
        perms = role_info.get("permissions", []) if role_info else []
        mapped_role = map_taiga_membership_role(role_name, bool(entry.get("is_admin", False)), perms)
        created_at = entry.get("created_at")
        key = (email, project_id)
        current = targets.get(key)
        if current is None:
            targets[key] = {"role": mapped_role, "created_at": created_at}
        else:
            # Keep strongest role and earliest known membership timestamp.
            strongest = max(int(current["role"]), int(mapped_role))
            current_created = current.get("created_at")
            earliest = current_created
            if created_at and (not earliest or created_at < earliest):
                earliest = created_at
            targets[key] = {"role": strongest, "created_at": earliest}

    return targets


def build_workspace_membership_created_targets(mapping, project_workspace_lookup):
    """
    Build earliest known Taiga membership created_at per (email, workspace_id).
    Returns dict: (email, workspace_id) -> created_at
    """
    targets = {}
    for entry in mapping.get("taiga_memberships", []) or []:
        if not isinstance(entry, dict):
            continue
        email = normalize_email(entry.get("email") or entry.get("user"))
        project_id = entry.get("plane_project_id")
        created_at = entry.get("created_at")
        if not email or not project_id or not created_at:
            continue
        workspace_id = get_project_workspace_id(None, project_id, project_workspace_lookup)
        if not workspace_id:
            continue
        key = (email, workspace_id)
        current = targets.get(key)
        if not current or created_at < current:
            targets[key] = created_at
    return targets


def collect_email_project_map(mapping):
    """Return dict: email -> set(project_id)."""
    email_projects = {}

    def add(email, project_id):
        if not email or "@" not in email:
            return
        email_projects.setdefault(email, set())
        if project_id:
            email_projects[email].add(project_id)

    for info in (mapping.get("issues") or {}).values():
        if not isinstance(info, dict):
            continue
        project_id = info.get("plane_project_id")
        add(info.get("author_email"), project_id)
        add(info.get("assigned_to_email"), project_id)
        for watcher in info.get("watchers_emails", []) or []:
            add(watcher, project_id)

    for info in (mapping.get("comments") or {}).values():
        if not isinstance(info, dict):
            continue
        add(info.get("author_email"), info.get("plane_project_id"))

    for info in (mapping.get("modules") or {}).values():
        if not isinstance(info, dict):
            continue
        add(info.get("author_email"), info.get("plane_project_id"))

    for info in (mapping.get("cycles") or {}).values():
        if not isinstance(info, dict):
            continue
        add(info.get("author_email"), info.get("plane_project_id"))

    for info in (mapping.get("pages") or {}).values():
        if not isinstance(info, dict):
            continue
        add(info.get("author_email"), info.get("plane_project_id"))
        add(info.get("last_modifier_email"), info.get("plane_project_id"))

    for info in (mapping.get("attachments") or {}).values():
        if not isinstance(info, dict):
            continue
        add(info.get("author_email"), info.get("plane_project_id"))

    for membership in mapping.get("taiga_memberships", []) or []:
        if not isinstance(membership, dict):
            continue
        add(membership.get("email") or membership.get("user"), membership.get("plane_project_id"))

    for email in mapping.get("taiga_emails", []) or []:
        add(email, None)

    return email_projects


def ensure_users_exist(cursor, mapping):
    """Create missing users and add them to workspace/project memberships."""
    email_projects = collect_email_project_map(mapping)
    if not email_projects:
        return 0

    template_user = get_template_user(cursor)
    template_ws_member = get_template_workspace_member(cursor)
    template_project_member = get_template_project_member(cursor)
    ws_view_props_json = to_json(template_ws_member["view_props"])
    ws_default_props_json = to_json(template_ws_member["default_props"])
    ws_issue_props_json = to_json(template_ws_member["issue_props"])
    pm_view_props_json = to_json(template_project_member["view_props"])
    pm_default_props_json = to_json(template_project_member["default_props"])
    pm_preferences_json = to_json(template_project_member["preferences"])

    # Cache project workspace ids
    project_workspace = {}
    for info in (mapping.get("projects") or {}).values():
        if not isinstance(info, dict):
            continue
        pid = info.get("plane_id")
        if not pid:
            continue
        workspace_id = get_project_workspace_id(cursor, pid, project_workspace)
        if workspace_id:
            project_workspace[pid] = workspace_id

    membership_role_targets = build_taiga_membership_role_targets(mapping)
    workspace_role_targets = {}
    for (email, project_id), role_info in membership_role_targets.items():
        workspace_id = get_project_workspace_id(cursor, project_id, project_workspace)
        if not workspace_id:
            continue
        key = (email, workspace_id)
        desired = int(role_info["role"])
        prev = workspace_role_targets.get(key)
        workspace_role_targets[key] = desired if prev is None else max(prev, desired)
    workspace_created_targets = {}
    for (email, project_id), role_info in membership_role_targets.items():
        workspace_id = get_project_workspace_id(cursor, project_id, project_workspace)
        if not workspace_id:
            continue
        created_at = role_info.get("created_at")
        if not created_at:
            continue
        key = (email, workspace_id)
        current = workspace_created_targets.get(key)
        if not current or created_at < current:
            workspace_created_targets[key] = created_at

    created = 0
    now = datetime.now(timezone.utc)

    for email, project_ids in email_projects.items():
        existing_id = lookup_user_id(cursor, email)
        if existing_id:
            user_id = existing_id
        else:
            user_id = str(uuid4())
            username = uuid4().hex
            local = email.split("@")[0]
            display_name = local[:255] or "User"
            cursor.execute(
                """
                INSERT INTO users (
                    password, last_login, id, username, mobile_number, email, first_name, last_name, avatar,
                    date_joined, created_at, updated_at, last_location, created_location, is_superuser, is_managed,
                    is_password_expired, is_active, is_staff, is_email_verified, is_password_autoset, token,
                    user_timezone, last_active, last_login_time, last_logout_time, last_login_ip, last_logout_ip,
                    last_login_medium, last_login_uagent, token_updated_at, is_bot, cover_image, display_name,
                    avatar_asset_id, cover_image_asset_id, bot_type, is_email_valid, masked_at
                ) VALUES (
                    %s, NULL, %s, %s, NULL, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, FALSE, FALSE,
                    FALSE, TRUE, FALSE, FALSE, TRUE, %s,
                    %s, NULL, NULL, NULL, %s, %s,
                    %s, %s, NULL, FALSE, NULL, %s,
                    NULL, NULL, NULL, %s, NULL
                )
                """,
                (
                    template_user["password"],
                    user_id,
                    username,
                    email,
                    display_name,
                    "",
                    template_user["avatar"],
                    now,
                    now,
                    now,
                    template_user["last_location"],
                    template_user["created_location"],
                    uuid4().hex * 2,
                    template_user["user_timezone"],
                    template_user["last_login_ip"],
                    template_user["last_logout_ip"],
                    template_user["last_login_medium"],
                    template_user["last_login_uagent"],
                    display_name,
                    template_user["is_email_valid"],
                ),
            )
            cache_key = normalize_email(email)
            if cache_key:
                USER_ID_CACHE[cache_key] = user_id
            created += 1

        # Ensure workspace membership for known projects
        for project_id in project_ids or []:
            workspace_id = get_project_workspace_id(cursor, project_id, project_workspace)
            if not workspace_id:
                continue

            email_norm = normalize_email(email)
            project_target = membership_role_targets.get((email_norm, project_id))
            desired_project_role = int(project_target["role"]) if project_target else int(template_project_member["role"])
            desired_workspace_role = int(
                workspace_role_targets.get((email_norm, workspace_id), desired_project_role)
            )
            workspace_membership_created_at = workspace_created_targets.get((email_norm, workspace_id)) or now
            project_membership_created_at = (project_target or {}).get("created_at") or workspace_membership_created_at

            cursor.execute(
                """
                SELECT id, role, created_at FROM workspace_members
                WHERE workspace_id = %s AND member_id = %s AND deleted_at IS NULL
                """,
                (workspace_id, user_id),
            )
            ws_row = cursor.fetchone()
            if not ws_row:
                cursor.execute(
                    """
                    INSERT INTO workspace_members (
                        created_at, updated_at, id, role, created_by_id, member_id, updated_by_id, workspace_id,
                        company_role, view_props, default_props, issue_props, is_active, deleted_at
                    ) VALUES (
                        %s, %s, %s, %s, NULL, %s, NULL, %s,
                        NULL, %s::jsonb, %s::jsonb, %s::jsonb, TRUE, NULL
                    )
                    """,
                    (
                        workspace_membership_created_at,
                        now,
                        str(uuid4()),
                        desired_workspace_role,
                        user_id,
                        workspace_id,
                        ws_view_props_json,
                        ws_default_props_json,
                        ws_issue_props_json,
                    ),
                )
            else:
                ws_id, existing_ws_role, existing_ws_created_at = ws_row
                target_ws_role = max(int(existing_ws_role), int(desired_workspace_role))
                should_update_created_at = (
                    workspace_membership_created_at
                    and existing_ws_created_at
                    and str(workspace_membership_created_at) < str(existing_ws_created_at)
                )
                if int(existing_ws_role) != target_ws_role or should_update_created_at:
                    if should_update_created_at:
                        cursor.execute(
                            "UPDATE workspace_members SET role = %s, created_at = %s, updated_at = %s WHERE id = %s",
                            (target_ws_role, workspace_membership_created_at, now, ws_id),
                        )
                    else:
                        cursor.execute(
                            "UPDATE workspace_members SET role = %s, updated_at = %s WHERE id = %s",
                            (target_ws_role, now, ws_id),
                        )

            cursor.execute(
                """
                SELECT id, role, created_at FROM project_members
                WHERE project_id = %s AND member_id = %s AND deleted_at IS NULL
                """,
                (project_id, user_id),
            )
            project_row = cursor.fetchone()
            if not project_row:
                cursor.execute(
                    """
                    INSERT INTO project_members (
                        created_at, updated_at, id, comment, role, created_by_id, member_id, project_id,
                        updated_by_id, workspace_id, view_props, default_props, sort_order, preferences,
                        is_active, deleted_at
                    ) VALUES (
                        %s, %s, %s, NULL, %s, NULL, %s, %s,
                        NULL, %s, %s::jsonb, %s::jsonb, %s, %s::jsonb,
                        TRUE, NULL
                    )
                    """,
                    (
                        project_membership_created_at,
                        now,
                        str(uuid4()),
                        desired_project_role,
                        user_id,
                        project_id,
                        workspace_id,
                        pm_view_props_json,
                        pm_default_props_json,
                        template_project_member["sort_order"],
                        pm_preferences_json,
                    ),
                )
            else:
                project_member_id, existing_project_role, existing_project_created_at = project_row
                should_update_project_created_at = (
                    project_membership_created_at
                    and existing_project_created_at
                    and str(project_membership_created_at) < str(existing_project_created_at)
                )
                if int(existing_project_role) != int(desired_project_role) or should_update_project_created_at:
                    if should_update_project_created_at:
                        cursor.execute(
                            "UPDATE project_members SET role = %s, created_at = %s, updated_at = %s WHERE id = %s",
                            (desired_project_role, project_membership_created_at, now, project_member_id),
                        )
                    else:
                        cursor.execute(
                            "UPDATE project_members SET role = %s, updated_at = %s WHERE id = %s",
                            (desired_project_role, now, project_member_id),
                        )

    return created


def update_issues(cursor, mapping):
    """Update created_at, updated_at, and created_by_id for all migrated issues."""
    issues = mapping.get("issues", {})
    updated = 0
    skipped = 0
    issue_type_cache = {}
    project_workspace_cache = {}

    print(f"\n📝 Updating {len(issues)} issues...")

    for taiga_key, info in issues.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        plane_id = info.get("plane_id")
        created_at = info.get("created_at")
        modified_at = info.get("modified_at")
        author_email = info.get("author_email")

        if not plane_id:
            skipped += 1
            continue

        # Build dynamic UPDATE query
        set_clauses = []
        params = []

        if created_at:
            set_clauses.append("created_at = %s")
            params.append(created_at)

        if modified_at:
            set_clauses.append("updated_at = %s")
            params.append(modified_at)

        # Map Taiga issue type -> Plane issue type (DB)
        taiga_issue_type = info.get("taiga_issue_type")
        if taiga_issue_type and info.get("plane_project_id"):
            project_id = info.get("plane_project_id")
            workspace_id = get_project_workspace_id(cursor, project_id, project_workspace_cache)

            if workspace_id:
                key = (workspace_id, taiga_issue_type.strip().lower())
                issue_type_id = issue_type_cache.get(key)
                if not issue_type_id:
                    cursor.execute(
                        """
                        SELECT it.id
                        FROM issue_types it
                        WHERE it.workspace_id = %s AND it.deleted_at IS NULL
                          AND LOWER(it.name) = %s
                        LIMIT 1
                        """,
                        (workspace_id, taiga_issue_type.strip().lower()),
                    )
                    row = cursor.fetchone()
                    if row:
                        issue_type_id = row[0]
                    else:
                        issue_type_id = str(uuid4())
                        cursor.execute(
                            """
                            INSERT INTO issue_types (
                                created_at, updated_at, id, name, description, logo_props,
                                created_by_id, updated_by_id, workspace_id, is_active, deleted_at,
                                is_default, level, external_id, external_source, is_epic
                            ) VALUES (
                                NOW(), NOW(), %s, %s, '', %s::jsonb,
                                NULL, NULL, %s, TRUE, NULL,
                                FALSE, 0, %s, 'taiga', FALSE
                            )
                            """,
                            (issue_type_id, taiga_issue_type.strip(), json.dumps({}), workspace_id, taiga_issue_type),
                        )
                    issue_type_cache[key] = issue_type_id

                if issue_type_id:
                    cursor.execute(
                        """
                        SELECT id FROM project_issue_types
                        WHERE project_id = %s AND issue_type_id = %s AND deleted_at IS NULL
                        """,
                        (project_id, issue_type_id),
                    )
                    if not cursor.fetchone():
                        cursor.execute(
                            """
                            INSERT INTO project_issue_types (
                                created_at, updated_at, deleted_at, id, level, is_default, created_by_id,
                                issue_type_id, project_id, updated_by_id, workspace_id
                            ) VALUES (
                                NOW(), NOW(), NULL, %s, 0, FALSE, NULL,
                                %s, %s, NULL, %s
                            )
                            """,
                            (str(uuid4()), issue_type_id, project_id, workspace_id),
                        )
                    set_clauses.append("type_id = %s")
                    params.append(issue_type_id)

        story_points = info.get("story_points")
        if isinstance(story_points, (int, float)):
            try:
                point_val = int(round(float(story_points)))
                set_clauses.append("point = %s")
                params.append(point_val)
            except Exception:
                pass

        # Look up the Plane user by email
        if author_email:
            plane_user_id = lookup_user_id(cursor, author_email)
            if plane_user_id:
                set_clauses.append("created_by_id = %s")
                params.append(plane_user_id)
                set_clauses.append("updated_by_id = %s")
                params.append(plane_user_id)

        if not set_clauses:
            skipped += 1
            continue

        params.append(plane_id)
        query = f"UPDATE issues SET {', '.join(set_clauses)} WHERE id = %s"

        try:
            cursor.execute(query, tuple(params))
            updated += 1
        except DBError as e:
            print(f"  ⚠️  Failed to update issue {plane_id}: {e}")
            skipped += 1

    print(f"  ✅ Updated: {updated}, Skipped: {skipped}")
    return updated


def update_comments(cursor, mapping):
    """Update created_at and actor_id for all migrated comments."""
    comments = mapping.get("comments", {})
    updated = 0
    skipped = 0

    print(f"\n💬 Updating {len(comments)} comments...")

    for taiga_key, info in comments.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        plane_id = info.get("plane_id")
        created_at = info.get("created_at")
        author_email = info.get("author_email")

        if not plane_id:
            skipped += 1
            continue

        # Build dynamic UPDATE query
        set_clauses = []
        params = []

        if created_at:
            set_clauses.append("created_at = %s")
            params.append(created_at)
            set_clauses.append("updated_at = %s")
            params.append(created_at)

        if author_email:
            plane_user_id = lookup_user_id(cursor, author_email)
            if plane_user_id:
                set_clauses.append("actor_id = %s")
                params.append(plane_user_id)
                set_clauses.append("created_by_id = %s")
                params.append(plane_user_id)
                set_clauses.append("updated_by_id = %s")
                params.append(plane_user_id)

        if not set_clauses:
            skipped += 1
            continue

        params.append(plane_id)
        query = f"UPDATE issue_comments SET {', '.join(set_clauses)} WHERE id = %s"

        try:
            cursor.execute(query, tuple(params))
            updated += 1
        except DBError as e:
            print(f"  ⚠️  Failed to update comment {plane_id}: {e}")
            skipped += 1

    print(f"  ✅ Updated: {updated}, Skipped: {skipped}")
    return updated


def update_issue_subscribers(cursor, mapping):
    """Reconcile Plane issue subscribers to match Taiga watchers."""
    issues = mapping.get("issues", {})
    created = 0
    removed = 0
    skipped = 0

    if not issues:
        return 0

    print(f"\n👀 Syncing subscribers for {len(issues)} issues...")

    for _, info in issues.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        issue_id = info.get("plane_id")
        project_id = info.get("plane_project_id")
        watchers = [normalize_email(w) for w in (info.get("watchers_emails", []) or [])]
        watcher_emails = sorted(set(w for w in watchers if w))

        if not issue_id or not project_id:
            skipped += 1
            continue

        workspace_id = get_project_workspace_id(cursor, project_id)
        if not workspace_id:
            skipped += 1
            continue

        author_user_id = lookup_user_id(cursor, info.get("author_email"))
        created_at = info.get("created_at") or datetime.now(timezone.utc)
        updated_at = info.get("modified_at") or created_at
        desired_subscribers = set()
        for watcher_email in watcher_emails:
            subscriber_id = lookup_user_id(cursor, watcher_email)
            if subscriber_id:
                desired_subscribers.add(subscriber_id)
            else:
                skipped += 1

        cursor.execute(
            """
            SELECT id, subscriber_id
            FROM issue_subscribers
            WHERE issue_id = %s AND deleted_at IS NULL
            """,
            (issue_id,),
        )
        existing_rows = cursor.fetchall() or []
        existing_by_subscriber = {row[1]: row[0] for row in existing_rows}

        for subscriber_id, issue_subscriber_id in existing_by_subscriber.items():
            if subscriber_id in desired_subscribers:
                continue
            cursor.execute(
                """
                UPDATE issue_subscribers
                SET deleted_at = %s, updated_at = %s, updated_by_id = %s
                WHERE id = %s
                """,
                (updated_at, updated_at, author_user_id, issue_subscriber_id),
            )
            removed += 1

        for subscriber_id in sorted(desired_subscribers):
            if subscriber_id in existing_by_subscriber:
                continue

            cursor.execute(
                """
                INSERT INTO issue_subscribers (
                    created_at, updated_at, id, created_by_id, issue_id, project_id,
                    subscriber_id, updated_by_id, workspace_id, deleted_at
                ) VALUES (
                    %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, NULL
                )
                """,
                (
                    created_at,
                    updated_at,
                    str(uuid4()),
                    author_user_id,
                    issue_id,
                    project_id,
                    subscriber_id,
                    author_user_id,
                    workspace_id,
                ),
            )
            created += 1

    print(f"  ✅ Created: {created}, Removed: {removed}, Skipped: {skipped}")
    return created


def update_modules(cursor, mapping):
    """Update created_at and created_by_id for migrated modules (from Taiga epics)."""
    modules = mapping.get("modules", {})
    updated = 0
    skipped = 0

    if not modules:
        return 0

    print(f"\n📦 Updating {len(modules)} modules...")

    for taiga_key, info in modules.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        plane_id = info.get("plane_id")
        created_at = info.get("created_at")
        author_email = info.get("author_email")

        if not plane_id:
            skipped += 1
            continue

        set_clauses = []
        params = []

        if created_at:
            set_clauses.append("created_at = %s")
            params.append(created_at)

        if author_email:
            plane_user_id = lookup_user_id(cursor, author_email)
            if plane_user_id:
                set_clauses.append("created_by_id = %s")
                params.append(plane_user_id)

        if not set_clauses:
            skipped += 1
            continue

        params.append(plane_id)
        query = f"UPDATE modules SET {', '.join(set_clauses)} WHERE id = %s"

        try:
            cursor.execute(query, tuple(params))
            updated += 1
        except DBError as e:
            print(f"  ⚠️  Failed to update module {plane_id}: {e}")
            skipped += 1

    print(f"  ✅ Updated: {updated}, Skipped: {skipped}")
    return updated


INLINE_TOKEN_RE = re.compile(r"(\*\*.+?\*\*|\*[^*\n]+?\*|\[[^\]]+\]\([^)]+\))")
URL_RE = re.compile(r"(https?://[^\s<]+)")


def _split_urls(text):
    parts = []
    last = 0
    for m in URL_RE.finditer(text):
        if m.start() > last:
            parts.append(("text", text[last : m.start()]))
        parts.append(("url", m.group(1)))
        last = m.end()
    if last < len(text):
        parts.append(("text", text[last:]))
    return parts


def _parse_inline(text):
    nodes = []
    if not text:
        return nodes
    text = text.replace("\xa0", " ")
    idx = 0
    for m in INLINE_TOKEN_RE.finditer(text):
        if m.start() > idx:
            nodes.extend(_parse_plain(text[idx : m.start()]))
        token = m.group(1)
        if token.startswith("**") and token.endswith("**"):
            nodes.append({"type": "text", "text": token[2:-2], "marks": [{"type": "strong"}]})
        elif token.startswith("*") and token.endswith("*"):
            nodes.append({"type": "text", "text": token[1:-1], "marks": [{"type": "em"}]})
        elif token.startswith("["):
            match = re.match(r"\[([^\]]+)\]\(([^)]+)\)", token)
            if match:
                label, href = match.group(1), match.group(2)
                nodes.append(
                    {
                        "type": "text",
                        "text": label,
                        "marks": [{"type": "link", "attrs": {"href": href}}],
                    }
                )
            else:
                nodes.extend(_parse_plain(token))
        else:
            nodes.extend(_parse_plain(token))
        idx = m.end()
    if idx < len(text):
        nodes.extend(_parse_plain(text[idx:]))
    return nodes


def _parse_plain(text):
    nodes = []
    if not text:
        return nodes
    text = text.replace("\xa0", " ")
    for kind, part in _split_urls(text):
        if not part:
            continue
        if kind == "url":
            nodes.append(
                {"type": "text", "text": part, "marks": [{"type": "link", "attrs": {"href": part}}]}
            )
        else:
            nodes.append({"type": "text", "text": part})
    return nodes


def _paragraph_from_lines(lines):
    content = []
    for i, line in enumerate(lines):
        if i > 0:
            content.append({"type": "hardBreak"})
        content.extend(_parse_inline(line))
    return {"type": "paragraph", "attrs": {"textAlign": None}, "content": content or []}


def build_page_description_json(content):
    """Build a basic ProseMirror JSON doc from markdown-like text."""
    text = (content or "").strip()
    if not text:
        return {"type": "doc", "content": []}

    lines = text.splitlines()
    blocks = []
    i = 0
    while i < len(lines):
        raw_line = lines[i]
        line = raw_line.replace("\xa0", " ").rstrip("\r")
        if not line.strip():
            i += 1
            continue

        if line.startswith("```"):
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                code_lines.append(lines[i].replace("\xa0", " ").rstrip("\r"))
                i += 1
            blocks.append({"type": "codeBlock", "content": [{"type": "text", "text": "\n".join(code_lines)}]})
            i += 1
            continue

        heading_match = re.match(r"^(#{1,6})\\s+(.*)$", line)
        if heading_match:
            level = len(heading_match.group(1))
            title = heading_match.group(2)
            blocks.append(
                {
                    "type": "heading",
                    "attrs": {"level": level, "textAlign": None},
                    "content": _parse_inline(title),
                }
            )
            i += 1
            continue

        list_match = re.match(r"^\s*([-*+])\s+(.*)$", line)
        if list_match:
            items = []
            while i < len(lines):
                m = re.match(r"^\s*([-*+])\s+(.*)$", lines[i].replace("\xa0", " ").rstrip("\r"))
                if not m:
                    break
                items.append(
                    {
                        "type": "listItem",
                        "content": [_paragraph_from_lines([m.group(2)])],
                    }
                )
                i += 1
            blocks.append({"type": "bulletList", "content": items})
            continue

        olist_match = re.match(r"^\s*\d+\.\s+(.*)$", line)
        if olist_match:
            items = []
            while i < len(lines):
                m = re.match(r"^\s*\d+\.\s+(.*)$", lines[i].replace("\xa0", " ").rstrip("\r"))
                if not m:
                    break
                items.append(
                    {
                        "type": "listItem",
                        "content": [_paragraph_from_lines([m.group(1)])],
                    }
                )
                i += 1
            blocks.append({"type": "orderedList", "content": items})
            continue

        if line.startswith("> "):
            quote_lines = []
            while i < len(lines) and lines[i].startswith("> "):
                quote_lines.append(lines[i][2:].replace("\xa0", " ").rstrip("\r"))
                i += 1
            blocks.append({"type": "blockquote", "content": [_paragraph_from_lines(quote_lines)]})
            continue

        para_lines = [line]
        i += 1
        while i < len(lines) and lines[i].replace("\xa0", " ").strip():
            para_lines.append(lines[i].replace("\xa0", " ").rstrip("\r"))
            i += 1
        blocks.append(_paragraph_from_lines(para_lines))

    return {"type": "doc", "content": blocks}


def build_page_description_html(content):
    """Build a simple HTML representation from markdown-like text."""
    doc = build_page_description_json(content)

    def render_nodes(nodes):
        out = []
        for node in nodes:
            if node.get("type") == "text":
                text = html.escape(node.get("text", ""))
                marks = node.get("marks") or []
                for mark in marks:
                    if mark.get("type") == "strong":
                        text = f"<strong>{text}</strong>"
                    elif mark.get("type") == "em":
                        text = f"<em>{text}</em>"
                    elif mark.get("type") == "link":
                        href = html.escape((mark.get("attrs") or {}).get("href", ""))
                        text = f"<a href=\"{href}\" target=\"_blank\" rel=\"noopener noreferrer\">{text}</a>"
                out.append(text)
            elif node.get("type") == "hardBreak":
                out.append("<br/>")
        return "".join(out)

    html_blocks = []
    for block in doc.get("content", []):
        btype = block.get("type")
        if btype == "paragraph":
            html_blocks.append(f"<p>{render_nodes(block.get('content') or [])}</p>")
        elif btype == "heading":
            level = (block.get("attrs") or {}).get("level", 1)
            level = max(1, min(6, int(level)))
            html_blocks.append(f"<h{level}>{render_nodes(block.get('content') or [])}</h{level}>")
        elif btype == "bulletList":
            items_html = []
            for item in block.get("content") or []:
                para = item.get("content") or []
                para_html = render_nodes((para[0].get("content") if para else []) or [])
                items_html.append(f"<li>{para_html}</li>")
            html_blocks.append(f"<ul>{''.join(items_html)}</ul>")
        elif btype == "orderedList":
            items_html = []
            for item in block.get("content") or []:
                para = item.get("content") or []
                para_html = render_nodes((para[0].get("content") if para else []) or [])
                items_html.append(f"<li>{para_html}</li>")
            html_blocks.append(f"<ol>{''.join(items_html)}</ol>")
        elif btype == "blockquote":
            para = block.get("content") or []
            para_html = render_nodes((para[0].get("content") if para else []) or [])
            html_blocks.append(f"<blockquote>{para_html}</blockquote>")
        elif btype == "codeBlock":
            code_text = ""
            if block.get("content"):
                code_text = block["content"][0].get("text", "")
            html_blocks.append(f"<pre><code>{html.escape(code_text)}</code></pre>")
    return "\n".join(html_blocks)


def get_project_page_context(cursor, project_id, fallback_user_ids):
    """Fetch project/workspace context and a safe owner fallback for pages."""
    cursor.execute(
        """
        SELECT workspace_id, created_by_id, project_lead_id, updated_by_id
        FROM projects
        WHERE id = %s
        """,
        (project_id,),
    )
    row = cursor.fetchone()
    if not row:
        return None

    workspace_id, created_by_id, project_lead_id, updated_by_id = row
    owner_id = created_by_id or project_lead_id or updated_by_id

    if not owner_id:
        for uid in fallback_user_ids:
            if uid:
                owner_id = uid
                break

    if not owner_id and workspace_id:
        cursor.execute(
            """
            SELECT member_id
            FROM workspace_members
            WHERE workspace_id = %s AND deleted_at IS NULL AND is_active = TRUE
            ORDER BY created_at ASC
            LIMIT 1
            """,
            (workspace_id,),
        )
        row = cursor.fetchone()
        if row:
            owner_id = row[0]

    return {
        "workspace_id": workspace_id,
        "owner_id": owner_id,
    }


def create_pages_via_db(cursor, mapping):
    """Create missing Plane pages directly in DB from Taiga wiki mapping."""
    pages = mapping.get("pages", {})
    if not pages:
        return 0, 0

    created = 0
    skipped = 0
    print(f"\n📄 Creating {len(pages)} pages via DB...")

    fallback_user_ids = list((mapping.get("users") or {}).values())
    project_ctx_cache = {}

    for taiga_key, info in pages.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        if info.get("plane_id"):
            skipped += 1
            continue

        project_id = info.get("plane_project_id")
        if not project_id:
            skipped += 1
            continue

        ctx = project_ctx_cache.get(project_id)
        if ctx is None:
            ctx = get_project_page_context(cursor, project_id, fallback_user_ids)
            project_ctx_cache[project_id] = ctx

        if not ctx or not ctx.get("workspace_id") or not ctx.get("owner_id"):
            print(f"  ⚠️  Skipping page '{taiga_key}': missing project/workspace owner context")
            skipped += 1
            continue

        slug = str(info.get("slug") or taiga_key)
        external_id = f"{project_id}:{slug}"

        cursor.execute(
            """
            SELECT p.id
            FROM pages p
            JOIN project_pages pp ON pp.page_id = p.id
            WHERE pp.project_id = %s
              AND pp.deleted_at IS NULL
              AND p.deleted_at IS NULL
              AND p.external_source = 'taiga'
              AND p.external_id = %s
            LIMIT 1
            """,
            (project_id, external_id),
        )
        existing = cursor.fetchone()
        if existing:
            info["plane_id"] = existing[0]
            skipped += 1
            continue

        created_at = info.get("created_at")
        modified_at = info.get("modified_at") or created_at
        author_email = info.get("author_email")
        modifier_email = info.get("last_modifier_email") or author_email

        created_by_id = lookup_user_id(cursor, author_email) if author_email else None
        updated_by_id = lookup_user_id(cursor, modifier_email) if modifier_email else None

        owner_id = created_by_id or ctx["owner_id"]
        if not owner_id:
            print(f"  ⚠️  Skipping page '{taiga_key}': unable to resolve owned_by user")
            skipped += 1
            continue

        page_id = str(uuid4())
        project_page_id = str(uuid4())

        name = (info.get("name") or slug).strip()[:255] or "Untitled Page"
        content = info.get("content") or ""
        description_json = json.dumps(build_page_description_json(content))
        description_html = build_page_description_html(content)
        description_stripped = (content or "").strip() or None

        cursor.execute(
            """
            INSERT INTO pages (
                created_at, updated_at, id, name, description, description_html, description_stripped,
                access, created_by_id, owned_by_id, updated_by_id, workspace_id, color, archived_at,
                is_locked, parent_id, view_props, logo_props, description_binary, is_global, deleted_at,
                moved_to_page, moved_to_project, external_id, external_source, sort_order
            ) VALUES (
                COALESCE(%s, NOW()), COALESCE(%s, COALESCE(%s, NOW())), %s, %s, %s::jsonb, %s, %s,
                0, %s, %s, %s, %s, '', NULL,
                FALSE, NULL, %s::jsonb, %s::jsonb, NULL, FALSE, NULL,
                NULL, NULL, %s, 'taiga', 65535
            )
            """,
            (
                created_at,
                modified_at,
                created_at,
                page_id,
                name,
                description_json,
                description_html,
                description_stripped,
                created_by_id,
                owner_id,
                updated_by_id,
                ctx["workspace_id"],
                json.dumps({"full_width": False}),
                json.dumps({}),
                external_id,
            ),
        )

        cursor.execute(
            """
            INSERT INTO project_pages (
                created_at, updated_at, id, created_by_id, page_id, project_id, updated_by_id, workspace_id, deleted_at
            ) VALUES (
                COALESCE(%s, NOW()), COALESCE(%s, COALESCE(%s, NOW())), %s, %s, %s, %s, %s, %s, NULL
            )
            """,
            (
                created_at,
                modified_at,
                created_at,
                project_page_id,
                created_by_id,
                page_id,
                project_id,
                updated_by_id,
                ctx["workspace_id"],
            ),
        )

        info["plane_id"] = page_id
        created += 1

    print(f"  ✅ Created: {created}, Skipped: {skipped}")
    return created, skipped


def update_pages(cursor, mapping):
    """Update timestamps/authorship for pages (created via API or DB)."""
    pages = mapping.get("pages", {})
    updated = 0
    skipped = 0

    if not pages:
        return 0

    print(f"\n🛠️  Updating {len(pages)} page metadata...")

    for taiga_key, info in pages.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        plane_id = info.get("plane_id")
        created_at = info.get("created_at")
        modified_at = info.get("modified_at") or created_at
        author_email = info.get("author_email")
        modifier_email = info.get("last_modifier_email") or author_email
        content = info.get("content") or ""

        if not plane_id:
            skipped += 1
            continue

        set_clauses = []
        params = []

        if created_at:
            set_clauses.append("created_at = %s")
            params.append(created_at)
        if modified_at:
            set_clauses.append("updated_at = %s")
            params.append(modified_at)

        if author_email:
            plane_user_id = lookup_user_id(cursor, author_email)
            if plane_user_id:
                set_clauses.append("created_by_id = %s")
                params.append(plane_user_id)

        if modifier_email:
            plane_user_id = lookup_user_id(cursor, modifier_email)
            if plane_user_id:
                set_clauses.append("updated_by_id = %s")
                params.append(plane_user_id)

        if content:
            description_json = json.dumps(build_page_description_json(content))
            description_html = build_page_description_html(content)
            description_stripped = (content or "").strip() or None
            set_clauses.append("description = %s::jsonb")
            params.append(description_json)
            set_clauses.append("description_html = %s")
            params.append(description_html)
            set_clauses.append("description_stripped = %s")
            params.append(description_stripped)

        if not set_clauses:
            skipped += 1
            continue

        params.append(plane_id)
        query = f"UPDATE pages SET {', '.join(set_clauses)} WHERE id = %s"

        try:
            cursor.execute(query, tuple(params))
            # Keep project_pages in sync for UI attribution.
            pp_set = []
            pp_params = []
            if created_at:
                pp_set.append("created_at = %s")
                pp_params.append(created_at)
            if modified_at:
                pp_set.append("updated_at = %s")
                pp_params.append(modified_at)
            if author_email:
                plane_user_id = lookup_user_id(cursor, author_email)
                if plane_user_id:
                    pp_set.append("created_by_id = %s")
                    pp_params.append(plane_user_id)
            if modifier_email:
                plane_user_id = lookup_user_id(cursor, modifier_email)
                if plane_user_id:
                    pp_set.append("updated_by_id = %s")
                    pp_params.append(plane_user_id)
            if pp_set:
                pp_params.append(plane_id)
                cursor.execute(
                    f"UPDATE project_pages SET {', '.join(pp_set)} WHERE page_id = %s",
                    tuple(pp_params),
                )
            updated += 1
        except DBError as e:
            print(f"  ⚠️  Failed to update page {plane_id}: {e}")
            skipped += 1

    print(f"  ✅ Updated: {updated}, Skipped: {skipped}")
    return updated


def update_attachments(cursor, mapping):
    """Update file_assets timestamps/authorship for migrated attachments."""
    attachments = mapping.get("attachments", {})
    updated = 0
    skipped = 0

    if not attachments:
        return 0

    print(f"\n📎 Updating {len(attachments)} attachments...")

    for taiga_key, info in attachments.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        asset_id = info.get("asset_id")
        created_at = info.get("created_at")
        modified_at = info.get("modified_at") or created_at
        author_email = info.get("author_email")

        if not asset_id:
            skipped += 1
            continue

        set_clauses = []
        params = []

        if created_at:
            set_clauses.append("created_at = %s")
            params.append(created_at)
        if modified_at:
            set_clauses.append("updated_at = %s")
            params.append(modified_at)

        if author_email:
            plane_user_id = lookup_user_id(cursor, author_email)
            if plane_user_id:
                set_clauses.append("created_by_id = %s")
                params.append(plane_user_id)
                set_clauses.append("updated_by_id = %s")
                params.append(plane_user_id)
                set_clauses.append("user_id = %s")
                params.append(plane_user_id)

        set_clauses.append("is_uploaded = TRUE")

        if not set_clauses:
            skipped += 1
            continue

        params.append(asset_id)
        query = f"UPDATE file_assets SET {', '.join(set_clauses)} WHERE id = %s"

        try:
            cursor.execute(query, tuple(params))
            updated += 1
        except DBError as e:
            print(f"  ⚠️  Failed to update attachment {asset_id}: {e}")
            skipped += 1

    print(f"  ✅ Updated: {updated}, Skipped: {skipped}")
    return updated


def update_issue_activities(cursor, mapping):
    """Update issue activity actor and timestamps from Taiga metadata."""
    issues = mapping.get("issues", {})
    if not issues:
        return 0

    updated = 0
    print(f"\n🧭 Updating activity actors for {len(issues)} issues...")

    for info in issues.values():
        if not isinstance(info, dict):
            continue
        issue_id = info.get("plane_id")
        project_id = info.get("plane_project_id")
        if not issue_id or not project_id:
            continue

        created_at = info.get("created_at")
        author_email = info.get("author_email")
        last_activity_at = info.get("last_activity_at") or info.get("modified_at")
        last_activity_email = info.get("last_activity_email") or author_email

        author_id = lookup_user_id(cursor, author_email) if author_email else None
        last_actor_id = lookup_user_id(cursor, last_activity_email) if last_activity_email else None

        if author_id:
            cursor.execute(
                """
                UPDATE issue_activities
                SET actor_id = %s, created_by_id = %s, updated_by_id = %s,
                    created_at = COALESCE(%s, created_at), updated_at = COALESCE(%s, updated_at)
                WHERE issue_id = %s AND project_id = %s AND verb = 'created'
                """,
                (author_id, author_id, author_id, created_at, created_at, issue_id, project_id),
            )

        if last_actor_id:
            cursor.execute(
                """
                UPDATE issue_activities
                SET actor_id = %s, created_by_id = %s, updated_by_id = %s,
                    created_at = COALESCE(%s, created_at), updated_at = COALESCE(%s, updated_at)
                WHERE issue_id = %s AND project_id = %s AND verb = 'updated'
                """,
                (last_actor_id, last_actor_id, last_actor_id, last_activity_at, last_activity_at, issue_id, project_id),
            )

        updated += 1

    print(f"  ✅ Updated: {updated}")
    return updated


def update_cycles(cursor, mapping):
    """Update created_at and created_by_id for migrated cycles."""
    cycles = mapping.get("cycles", {})
    updated = 0
    skipped = 0

    if not cycles:
        return 0

    print(f"\n🗓️  Updating {len(cycles)} cycles...")

    for taiga_key, info in cycles.items():
        if not isinstance(info, dict):
            skipped += 1
            continue

        plane_id = info.get("plane_id")
        created_at = info.get("created_at")
        author_email = info.get("author_email")
        start_date = info.get("start_date")
        end_date = info.get("end_date")

        if not plane_id:
            skipped += 1
            continue

        set_clauses = []
        params = []

        if created_at:
            set_clauses.append("created_at = %s")
            params.append(created_at)
        if start_date:
            set_clauses.append("start_date = %s")
            params.append(start_date)
        if end_date:
            set_clauses.append("end_date = %s")
            params.append(end_date)

        if author_email:
            plane_user_id = lookup_user_id(cursor, author_email)
            if plane_user_id:
                set_clauses.append("created_by_id = %s")
                params.append(plane_user_id)

        if not set_clauses:
            skipped += 1
            continue

        params.append(plane_id)
        query = f"UPDATE cycles SET {', '.join(set_clauses)} WHERE id = %s"
        try:
            cursor.execute(query, tuple(params))
            updated += 1
        except DBError as e:
            print(f"  ⚠️  Failed to update cycle {plane_id}: {e}")
            skipped += 1

    print(f"  ✅ Updated: {updated}, Skipped: {skipped}")
    return updated


# ==========================================
# MAIN
# ==========================================


def main():
    mapping_file = sys.argv[1] if len(sys.argv) > 1 else MAPPING_FILE
    reset_runtime_caches()

    print("=" * 60)
    print("🔧 TAIGA → PLANE.SO MIGRATION (Layer 2: DB Override)")
    print(f"   Wiki pages via DB: {'ON' if MIGRATE_WIKI_PAGES_VIA_DB else 'OFF'}")
    print("=" * 60)

    mapping = load_mapping(mapping_file)
    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        users_created = ensure_users_exist(cursor, mapping)
        pages_created = 0
        if MIGRATE_WIKI_PAGES_VIA_DB:
            pages_created, _ = create_pages_via_db(cursor, mapping)
        issues_updated = update_issues(cursor, mapping)
        comments_updated = update_comments(cursor, mapping)
        subscribers_created = update_issue_subscribers(cursor, mapping)
        modules_updated = update_modules(cursor, mapping)
        pages_updated = update_pages(cursor, mapping)
        attachments_updated = update_attachments(cursor, mapping)
        activities_updated = update_issue_activities(cursor, mapping)
        cycles_updated = update_cycles(cursor, mapping)

        print(f"\n{'=' * 60}")
        print("📊 DB OVERRIDE SUMMARY")
        print(f"{'=' * 60}")
        print(f"  Issues updated:   {issues_updated}")
        print(f"  Comments updated: {comments_updated}")
        print(f"  Subscribers created: {subscribers_created}")
        print(f"  Modules updated:  {modules_updated}")
        print(f"  Pages created:    {pages_created}")
        print(f"  Pages updated:    {pages_updated}")
        print(f"  Attachments updated: {attachments_updated}")
        print(f"  Activities updated: {activities_updated}")
        print(f"  Cycles updated:   {cycles_updated}")
        print(f"  Users created:    {users_created}")

        # Confirm commit
        print("\n⚠️  Committing changes to database...")
        conn.commit()
        print("✅ All changes committed successfully!")

    except Exception as e:
        print(f"\n❌ Error during DB override: {e}")
        print("🔄 Rolling back all changes...")
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()
        print("\n🔌 Database connection closed.")


if __name__ == "__main__":
    main()
